return {
 WoodenTrainer={Name="Wooden Trainer",Damage=10,Cooldown=.60,Cost=0,Color=Color3.fromRGB(190,140,80)},
 BronzeShortblade={Name="Bronze Shortblade",Damage=18,Cooldown=.50,Cost=250,Color=Color3.fromRGB(225,155,70)},
 KnightLongsword={Name="Knight's Longsword",Damage=35,Cooldown=.80,Cost=1200,Color=Color3.fromRGB(190,215,235)},
 SunfangGreatsword={Name="Sunfang Greatsword",Damage=70,Cooldown=1.20,Cost=5000,Color=Color3.fromRGB(255,195,60)},
 EmberhornCleaver={Name="Emberhorn's Cleaver",Damage=95,Cooldown=1.10,Color=Color3.fromRGB(255,85,45)},
 GlacialEdge={Name="Glacial Edge",Damage=60,Cooldown=.55,Color=Color3.fromRGB(84,218,255)},
}
