return {
 Font = Enum.Font.BuilderSansMedium,
 HeadingFont = Enum.Font.BuilderSansBold,
 TextMax = 24, ButtonTextMax = 20,
 Corner = .055, ButtonCorner = .12,
 HoverScale = 1.025, PressScale = .97,
 Transition = .16, PanelTransition = .2,
 HoverVolume = .055, ClickVolume = .12,
 HoverSound = "rbxasset://sounds/volume_slider.ogg",
 ClickSound = "rbxasset://sounds/volume_slider.ogg",
 HoverPitch = 1.8, ClickPitch = 1.15,
 SoundInterval = .055,
}
